In [19]:
import os
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score,cross_validate
from sklearn.metrics import precision_score, recall_score, f1_score,accuracy_score
from sklearn.metrics import confusion_matrix,ConfusionMatrixDisplay,f1_score,recall_score,precision_score,accuracy_score

In [20]:
dir = os.getcwd()
credit_card_df = pd.read_csv('../data/creditcard.csv')

duplicate_values = credit_card_df.duplicated()

credit_card_df = credit_card_df.drop_duplicates()

In [21]:
X =credit_card_df[ ['V14', 'V17', 'V10', 'V12', 'V4', 'V28', 'V26', 'V27', 'Time', 'V7', 'V20', 'V8', 'V9', 'V25', 'V1', 'V6', 'V22', 'V18', 'V21', 'V2']]
y = credit_card_df['Class']

X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size= 0.2,
    random_state=42,
    stratify=y
)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [22]:
n_neighbors = [1,5,20]

knn_precisions= []
knn_recalls =[]
knn_f1scores = []

In [23]:
#knn hyperparameters
for i in n_neighbors:
    knn_model_ht = KNeighborsClassifier(n_neighbors=i)
    knn_model_ht.fit(X_train_scaled,y_train)
    y_pred_knn_ht=knn_model_ht.predict(X_test_scaled)
    
    precision_knn_ht = precision_score(y_test,y_pred_knn_ht)
    knn_precisions.append(precision_knn_ht)
    
    recall_knn_ht = recall_score(y_test,y_pred_knn_ht)
    knn_recalls.append(recall_knn_ht)
    
    f1_knn_ht = f1_score(y_test,y_pred_knn_ht)
    knn_f1scores.append(f1_knn_ht)
    
knn_result_ht_df = pd.DataFrame({
    'Parameter Value' : n_neighbors,
    'Precision' :knn_precisions,
    'Recall' :knn_recalls,
    'F1' : knn_f1scores
})

knn_result_ht_df

   Parameter Value  Precision    Recall        F1
0                1   0.809524  0.715789  0.759777
1                5   0.956522  0.694737  0.804878
2               20   0.915493  0.684211  0.783133

In [24]:
max_depthes = [2,5,10,7,20,None]

In [25]:
Decision_tree_precisions= []
Decision_tree_recalls =[]
Decision_tree_f1scores = [] 
for i in max_depthes:
    Decision_tree_model_ht = DecisionTreeClassifier(max_depth=i)
    Decision_tree_model_ht.fit(X_train_scaled,y_train)
    y_pred_Decision_tree_ht=Decision_tree_model_ht.predict(X_test_scaled)
    
    precision_Decision_tree_ht = precision_score(y_test,y_pred_Decision_tree_ht)
    Decision_tree_precisions.append(precision_Decision_tree_ht)
    
    recall_Decision_tree_ht = recall_score(y_test,y_pred_Decision_tree_ht)
    Decision_tree_recalls.append(recall_Decision_tree_ht)
    
    f1_Decision_tree_ht = f1_score(y_test,y_pred_Decision_tree_ht)
    Decision_tree_f1scores.append(f1_Decision_tree_ht)
    
Decision_tree_result_ht_df = pd.DataFrame({
    'Parameter Value' : max_depthes,
    'Precision' :Decision_tree_precisions,
    'Recall' :Decision_tree_recalls,
    'F1' : Decision_tree_f1scores
})

Decision_tree_result_ht_df

   Parameter Value  Precision    Recall        F1
0              2.0   0.835443  0.694737  0.758621
1              5.0   0.868421  0.694737  0.771930
2             10.0   0.857143  0.694737  0.767442
3              7.0   0.890411  0.684211  0.773810
4             20.0   0.800000  0.673684  0.731429
5              NaN   0.783133  0.684211  0.730337

In [26]:
Random_forest_precisions= []

Random_forest_recalls =[]

Random_forest_f1scores = [] 

for i in max_depthes:
    RF_model_ht = RandomForestClassifier(max_depth=i)
    RF_model_ht.fit(X_train_scaled,y_train)
    y_pred_RF_ht=RF_model_ht.predict(X_test_scaled)
    
    precision_RF_ht = precision_score(y_test,y_pred_RF_ht)
    Random_forest_precisions.append(precision_RF_ht)
    
    recall_RF_ht = recall_score(y_test,y_pred_RF_ht)
    Random_forest_recalls.append(recall_RF_ht)
    
    f1_RF_ht = f1_score(y_test,y_pred_RF_ht)
    Random_forest_f1scores.append(f1_RF_ht)
    


RF_result_ht_df = pd.DataFrame({
'Parameter Value' : max_depthes,
'Precision' :Random_forest_precisions,
'Recall' :Random_forest_recalls,
'F1' : Random_forest_f1scores
})
RF_result_ht_df

   Parameter Value  Precision    Recall        F1
0              2.0   0.842105  0.505263  0.631579
1              5.0   0.942857  0.694737  0.800000
2             10.0   0.971429  0.715789  0.824242
3              7.0   0.971831  0.726316  0.831325
4             20.0   0.972222  0.736842  0.838323
5              NaN   0.972222  0.736842  0.838323

In [27]:
Thresholds =[0.3,0.5,0.6,0.7]

In [28]:
Logistic_regression_precisions= []
Logistic_regression_recalls =[]
Logistic_regression_f1scores = [] 

for i in Thresholds:
    Logistic_regression_model_ht = LogisticRegression()
    Logistic_regression_model_ht.fit(X_train_scaled,y_train)
    proba =Logistic_regression_model_ht.predict_proba(X_test_scaled)[:,1]
    y_pred_Logistic_regression_ht = Logistic_regression_model_ht.predict(X_test_scaled)
    y_pred_Logistic_regression_ht = (proba >= i).astype(int)
    
    Logistic_regression_ht = precision_score(y_test,y_pred_Logistic_regression_ht)
    Logistic_regression_precisions.append(Logistic_regression_ht)
    
    recall_Logistic_regression_ht = recall_score(y_test,y_pred_Logistic_regression_ht)
    Logistic_regression_recalls.append(recall_Logistic_regression_ht)
    
    Logistic_regression_ht = f1_score(y_test,y_pred_Logistic_regression_ht)
    Logistic_regression_f1scores.append(Logistic_regression_ht)
    
Logistic_regression_result_ht_df = pd.DataFrame({
'Parameter Value' : Thresholds,
'Precision' :Logistic_regression_precisions,
'Recall' :Logistic_regression_recalls,
'F1' : Logistic_regression_f1scores
})

print(Logistic_regression_result_ht_df)

   Parameter Value  Precision    Recall        F1
0              0.3   0.835616  0.642105  0.726190
1              0.5   0.843750  0.568421  0.679245
2              0.6   0.836066  0.536842  0.653846
3              0.7   0.842105  0.505263  0.631579

In [29]:
Decision_tree_precisions= []

Decision_tree_recalls =[]

Decision_tree_f1scores = [] 

for i in Thresholds:

    Decision_tree_model_ht = DecisionTreeClassifier(max_depth=7)

    Decision_tree_model_ht.fit(X_train_scaled,y_train)

    proba =Decision_tree_model_ht.predict_proba(X_test_scaled)[:,1]

    y_pred_Decision_tree_ht = Decision_tree_model_ht.predict(X_test_scaled)

    y_pred_Decision_tree_ht = (proba >= i).astype(int)

    Decision_tree_ht = precision_score(y_test,y_pred_Decision_tree_ht)

    Decision_tree_precisions.append(Decision_tree_ht)

    recall_Decision_tree_ht = recall_score(y_test,y_pred_Decision_tree_ht)

    Decision_tree_recalls.append(recall_Decision_tree_ht)

    Decision_tree_ht = f1_score(y_test,y_pred_Decision_tree_ht)

    Decision_tree_f1scores.append(Decision_tree_ht)

Decision_tree_result_ht_df = pd.DataFrame({

'Parameter Value' : Thresholds,

'Precision' :Decision_tree_precisions,

'Recall' : Decision_tree_recalls,

'F1' : Decision_tree_f1scores

})

print(Decision_tree_result_ht_df)

   Parameter Value  Precision    Recall        F1
0              0.3   0.868421  0.694737  0.771930
1              0.5   0.878378  0.684211  0.769231
2              0.6   0.902778  0.684211  0.778443
3              0.7   0.902778  0.684211  0.778443

In [30]:
Random_forest_precisions= []

Random_forest_recalls =[]

Random_forest_f1scores = [] 

for i in Thresholds:

    Random_forest_model_ht = RandomForestClassifier(max_depth=7)

    Random_forest_model_ht.fit(X_train_scaled,y_train)

    proba =Random_forest_model_ht.predict_proba(X_test_scaled)[:,1]

    y_pred_Random_forest_ht = Random_forest_model_ht.predict(X_test_scaled)

    y_pred_Random_forest_ht = (proba >= i).astype(int)

    Random_forest_ht = precision_score(y_test,y_pred_Random_forest_ht)

    Random_forest_precisions.append(Random_forest_ht)

    recall_Random_forest_ht = recall_score(y_test,y_pred_Random_forest_ht)

    Random_forest_recalls.append(recall_Random_forest_ht)

    Random_forest_ht = f1_score(y_test,y_pred_Random_forest_ht)

    Random_forest_f1scores.append(Random_forest_ht)

Random_forest_result_ht_df = pd.DataFrame({

'Parameter Value' : Thresholds,

'Precision' :Random_forest_precisions,

'Recall' : Random_forest_recalls,

'F1' : Random_forest_f1scores

})

print(Random_forest_result_ht_df)

   Parameter Value  Precision    Recall        F1
0              0.3   0.878049  0.757895  0.813559
1              0.5   0.971831  0.726316  0.831325
2              0.6   0.984848  0.684211  0.807453
3              0.7   0.983871  0.642105  0.777070